name = "workers-airtable-form"
type = "javascript"

account_id = "85cd22477a0c077c8c481cda586f660de4c63"

workers_dev = true

[vars]
AIRTABLE_BASE_ID = "app1xlNtRnxVn6BnA"
AIRTABLE_TABLE_NAME = "Form Submissions"
FORM_URL = "workers-airtable-form-4v3.pages.dev"
